### ISSUE TITLE
Is this something I can build today?

### ISSUE THREAD

**Issue by rthorntn** [bartei/rotary-controller-f4#6]
[Sorry about adding it as an issue, usually a discussion is better but discussions aren't enabled]

Hi,

Congratulations on this amazing product and thanks for all your work on this..

I would like one for my mill and another for my lathe (both have Sino TTL glass scales), I can surface-mount solder, although the LQFP64 STM32F411 looks tricky, did you consider using a BlackPill?

So how can I get going with this?

Thanks again.

**Comment by bartei** [comment]
Hi!

I would recommend to purchase a board already assembled programmed and tested from the store: 
[https://www.provvedo.com](https://www.provvedo.com)

I am pricing the boards very reasonably and the LQFP64 chip is readily available and cheap to purchase on the market.

Sino scales work very well and their DB9 pinout matches the pinout of my DRO board so you should have no problem with those.

I sell also DB9 screw terminal adapters on the store if you need to rewire the scales and don't want to fiddle with soldering tiny wires.

Thanks for pointing out that discussions are not enabled, I will check how to enable them :100:
